--- 
abstract: Automatically build tab sets for a controller
author: 
  - Jason Kohles C<< <email@jasonkohles.com> >> L<http://www.jasonkohles.com>
build_requires: 
  Catalyst::Runtime: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CatalystX-Controller-Tabs
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Controller: 0
  NEXT: 0
version: 0.02
